name: Mender build on push
env:
        DOCKER_CLI_EXPERIMENTAL: enabled

on:
    push:
            tags:
                - v[0-9]+.[0-9]+.[0-9]+
                - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build and push dashboard image
                steps:
                        - name: Set tag
                          run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}
                        - name: Checkout project
                          uses: actions/checkout@v2
                        - name: Run build script
                          run: sudo ./build.sh
                        - name: Release image to placeholder or release
                          uses: meeDamian/github-release@v1.0.0
                          with:
                            gzip: false
                            files: "deploy/umbrel-os*"
                            token: ${{ secrets.GITHUB_TOKEN }}
                            allow_override: true
