name: Mender build on push
env:
        DOCKER_CLI_EXPERIMENTAL: enabled

on:
    push:
            tags:
                - v[0-9]+.[0-9]+.[0-9]+
                - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
        build:
                runs-on: ubuntu-18.04
                steps:
                        - name: Set tag
                          run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}
                        - name: Checkout project
                          uses: actions/checkout@v2
                        - name: Run build script
                          run: sudo ./build.sh
                        - name: Upload artifacts
                          uses: actions/upload-artifact@v2
                          with:
                            name: umbrel-os
                            path: mender-convert/deploy/*.img.xz
